# CSV-Trained EfficientNet B5 Inference Configuration
# Using the model trained on CSV dataset with 5 classes
model:
  name: "efficientnet"
  variant: "b5"
  weights_path: "model_weights/efficientnet/b5/efficientnet_b5_training_20250806_142450/best.pt"
  num_classes: 5  # CSV dataset has 5 classes

inference:
  image_dir: "DATA/inference/ecotaxa_infer_set"
  batch_size: 32
  top_k: 5
  device: "cuda"
  save_csv: true
  output_path: "outputs/csv_model_inference22.csv"

# Optional preprocessing during inference
preprocessing:
  scalebar_removal: true
  
wandb:
  log_results: false  # Keep simple for testing
  tags: ["inference", "efficientnet", "b5", "csv_dataset"]
  notes: "Inference with CSV-trained EfficientNet B5 model (5 classes)"
