# Quick DenseNet Inference Configuration
model:
  name: "densenet"
  variant: "121"
  weights_path: "model_weights/densenet/121/best_run_experiment/best.pt"

inference:
  batch_size: 64
  top_k: 3
  device: "cuda"
  save_csv: true
  output_path: "outputs/densenet_121_quick_inference.csv"

preprocessing:
  scalebar_removal: true

wandb:
  log_results: false
  tags: ["inference", "densenet", "121", "quick"]
  notes: "Quick inference test with DenseNet 121"
