# ============================================================
# EfficientNet B5 Production Configuration with ALL OPTIONS
# ============================================================

run_name: "Reproduce_Best_ResNet"  # Custom run name for testing


# DATA CONFIGURATION
data:
  dataset_path: "DATA/final_dataset"  # Path to your dataset 
  
# PROJECT CONFIGURATION
project:
  name: "YourWandBProjectName"     # W&B project name

# MODEL CONFIGURATION
model:
  name: "resnet"      # Options: "efficientnet", "resnet", "densenet", "yolov11"
  variant: "152"             
  pretrained: true          # Use pretrained weights
  freeze_backbone: false    # Freeze backbone layers
  input_size: 224           # Input image size (224, 256, 384, etc.)
  num_classes: 76           # Number of output classes


# TRAINING CONFIGURATION
training:
  batch_size: 64               # Training batch size
  learning_rate: 0.000001        # Initial learning rate
  weight_decay: 0.0000005           # Weight decay (L2 regularization)
  epochs: 30                    # Maximum number of epochs
  optimizer: "adamw"           # Options: "adam", "adamw", "sgd", "rmsprop"
  early_stopping_patience: 15  # Early stopping patience
  device: "cuda"               # Options: "cuda", "cpu", "auto"
  num_workers: 8               # Number of data loader workers

# LOSS CONFIGURATION
loss:
  type: "labelsmoothing"       # Options: "focal", "labelsmoothing", "weighted"
  label_smoothing: 0.05133367510889371         # Label smoothing parameter (0.0-1.0)
  use_per_class_alpha: true    # Use per-class weights

# WEIGHTS & BIASES CONFIGURATION
wandb:
  log_results: false
  tags: ["reproduce", "resnet", "152"]
  notes: "Reproduce Best ResNet 152"