# EcoTaxa Export Preprocessing Configuration
# For EcoTaxa TSV exports with taxonomic hierarchy

input_source:
  type: "ecotaxa"
  data_path: "DATA/ecotaxa_export"
  metadata_file: "ecotaxa_export.tsv"
  separator: "\t"

preprocessing:
  scalebar_removal:
    enabled: true
    model_path: "models/model_weights/scale_bar_remover/best.pt"
    confidence: 0.4
    img_size: 416
  
  grayscale_conversion:
    enabled: false  # EcoTaxa images often need to preserve color
    mode: "RGB"
  
  image_filtering:
    min_images_per_class: 10
    max_images_per_class: null
    skip_corrupted_images: true
  
  data_splitting:
    train_ratio: 0.7
    val_ratio: 0.2
    test_ratio: 0.1
    stratified: true
    random_seed: 42
  
  augmentation:
    enabled: true
    target_images_per_class: 800
    max_copies_per_image: 6
    techniques:
      horizontal_flip: 0.5
      vertical_flip: 0.2
      rotate_90: 0.3
      brightness_contrast: 0.3  # More conservative for scientific images
      hue_saturation: 0.2
      
output:
  base_path: "DATA/processed_ecotaxa"
  processed_path: "DATA/processed_ecotaxa/processed"
  final_dataset_path: "DATA/processed_ecotaxa/final_dataset"
  create_dataset_yaml: true
  
logging:
  wandb_enabled: true
  log_class_distribution: true
  log_sample_images: true
  log_processing_times: true
