# Simple Hierarchical Dataset Preprocessing Configuration
# For datasets already organized by class in folders
input_source:
  type: "hierarchical"
  data_path: "DATA/sample_hierarchical"
  subdirs: []  # Empty = direct class folders under data_path

preprocessing:
  scalebar_removal:
    enabled: true
    model_path: "models/model_weights/scale_bar_remover/best.pt"
    confidence: 0.4
    img_size: 416
  
  grayscale_conversion:
    enabled: true
    mode: "RGB"
  
  image_filtering:
    min_images_per_class: 10
    max_images_per_class: null
    skip_corrupted_images: true
  
  data_splitting:
    train_ratio: 0.7
    val_ratio: 0.2
    test_ratio: 0.1
    stratified: true
    random_seed: 42
  
  augmentation:
    enabled: true
    target_images_per_class: 50  # Even lower target for quick processing
    max_copies_per_image: 5
    techniques:
      horizontal_flip: 0.5
      vertical_flip: 0.2
      rotate_90: 0.3
      brightness_contrast: 0.4
      hue_saturation: 0.3
      
output:
  base_path: "DATA/sample_hierarchical"
  processed_path: "DATA/sample_hierarchical_processed"
  final_dataset_path: "DATA/sample_hierarchical_final_dataset"
  create_dataset_yaml: true
  
logging:
  wandb_enabled: false  # Simple config without W&B
  log_class_distribution: true
  log_sample_images: false
  log_processing_times: true
