# Fast Experiment Configuration for DenseNet
model:
  name: "densenet"
  variant: "121"
  pretrained: true
  freeze_backbone: false

training:
  batch_size: 64
  learning_rate: 0.002
  weight_decay: 0.1
  epochs: 1  # Shorter for quick experiments
  optimizer: "adamw"
  early_stopping_patience: 10

loss:
  type: "labelsmoothing"
  labelsmoothing_epsilon: 0.1

wandb:
  tags: ["experiment", "densenet", "121", "label_smoothing", "fast"]
  notes: "Quick experiment with DenseNet 121 and Label Smoothing"
