# ============================================================
# EfficientNet B5 Production Configuration with ALL OPTIONS
# ============================================================

# DATA CONFIGURATION
data:
  dataset_path: "DATA/sample_hierarchical_final_dataset"  # Path to dataset.yaml
  
# PROJECT CONFIGURATION
project:
  name: "YOLOv11Classification500"     # W&B project name
  # run_name: "custom_run_name"        # Optional: custom run name
  # group: "experiment_group"          # Optional: experiment group

# MODEL CONFIGURATION
model:
  name: "efficientnet"      # Options: "efficientnet", "resnet", "densenet", "yolov11"
  variant: "b5"             # EfficientNet variants: "b0"-"b7", ResNet: "18","34","50","101","152"
  pretrained: true          # Use pretrained weights
  freeze_backbone: false    # Freeze backbone layers
  input_size: 224           # Input image size (224, 256, 384, etc.)
  num_classes: 5            # Number of output classes
  
  # Additional model options:
  # dropout_rate: 0.2              # Dropout rate (0.0-1.0)
  # use_se_blocks: true            # Use Squeeze-and-Excitation blocks

# TRAINING CONFIGURATION
training:
  batch_size: 32               # Training batch size
  learning_rate: 0.001         # Initial learning rate
  weight_decay: 0.01           # Weight decay (L2 regularization)
  epochs: 5                    # Maximum number of epochs
  optimizer: "adamw"           # Options: "adam", "adamw", "sgd", "rmsprop"
  early_stopping_patience: 15  # Early stopping patience
  device: "cuda"               # Options: "cuda", "cpu", "auto"
  num_workers: 8               # Number of data loader workers
  
  # Advanced training options:
  # gradient_clip_norm: 1.0      # Gradient clipping norm
  # mixed_precision: true        # Use automatic mixed precision
  # scheduler: "cosine"          # LR scheduler: "cosine", "step", "exponential"

# LOSS CONFIGURATION
loss:
  type: "labelsmoothing"       # Options: "focal", "labelsmoothing", "weighted"
  label_smoothing: 0.1         # Label smoothing parameter (0.0-1.0)
  use_per_class_alpha: true    # Use per-class weights
  
  # Focal loss options (when type: "focal"):
  # focal_alpha: 1.0             # Focal loss alpha parameter
  # focal_gamma: 2.0             # Focal loss gamma parameter

# WEIGHTS & BIASES CONFIGURATION
wandb:
  tags: ["production", "efficientnet", "b5", "label_smoothing"]
  notes: "Production EfficientNet B5 with label smoothing"
  
  # Additional W&B options:
  # log_model: true              # Log model to W&B
  # log_gradients: false         # Log gradient histograms
  # watch_model: true            # Watch model with W&B
